POST   http://localhost:3000/orden/
Content-Type: application/json

{
  "Guid": "5db74100ada622232c76e1f2",
  "Descripcion": "cono",
  "Size": "Mediano",
  "Sabor": "Vainilla",
  "Pack": "5db74166ada622232c76e1f3"
}







